<template>
  <el-card>
    <el-alert
      title="专病档案相当于病案室里的空间，录入病例之前需要新建专病档案。"
      type="info"
      show-icon
      class="mb-4"
    />

    <el-form ref="formRef" :model="form" :rules="rules" label-width="100px">
      <el-form-item label="档案号">
        <el-input v-model="form.code" disabled />
        <el-link type="primary" class="ml-2" @click="generateCode"> 自动生成 </el-link>
      </el-form-item>

      <el-form-item label="档案名称" prop="name">
        <el-input v-model="form.name" placeholder="请输入" />
      </el-form-item>

      <el-form-item label="档案描述" prop="desc">
        <el-input v-model="form.desc" type="textarea" placeholder="请输入" :rows="4" />
      </el-form-item>

      <el-form-item>
        <el-button type="primary" @click="submitForm" :loading="loading"> 添加 </el-button>
      </el-form-item>
    </el-form>
  </el-card>
</template>

<script lang="ts">
import { defineComponent, reactive, ref, onMounted } from 'vue';
import { ElMessage } from 'element-plus';
import { archiveCreate } from '../../api/archive'; // Adjust this path to your API utility file

// Define the expected structure for the data sent to archiveCreate
interface ArchiveCreateBody {
  archive_name: string;
  archive_description: string;
  // Note: archive_code is automatically generated by the backend,
  // so we don't send it in the request body for creation.
}

export default defineComponent({
  name: 'NewCaseFile',
  setup() {
    const formRef = ref<any>(null); // Use 'any' or more specific ElFormInstance if you have the type
    const loading = ref(false); // Reactive variable for loading state

    const form = reactive({
      code: '', // This is client-side generated for display, backend generates its own
      name: '',
      desc: '',
    });

    const rules = {
      name: [{ required: true, message: '请输入档案名称', trigger: 'blur' }],
      desc: [{ required: true, message: '请输入档案描述', trigger: 'blur' }],
    };

    const generateCode = () => {
      // Client-side generated code for display purposes.
      // The backend will generate the actual unique archive_code.
      const randomNumber = Math.floor(100000 + Math.random() * 900000);
      form.code = `B${randomNumber}`;
    };

    const submitForm = async () => {
      // Validate the form first
      const isValid = await formRef.value.validate();

      if (isValid) {
        loading.value = true; // Set loading to true when submission starts
        try {
          // Prepare the data payload for the backend
          const requestBody: ArchiveCreateBody = {
            archive_name: form.name,
            archive_description: form.desc,
          };

          // Call the backend API
          const response = await archiveCreate(requestBody);

          // Check the response from your backend
          if (response && response.code === 200) {
            ElMessage.success('档案添加成功！');
            // Optionally, reset the form or navigate away
            formRef.value.resetFields(); // Resets validated fields
            form.code = ''; // Clear the client-side generated code as well
            generateCode(); // Generate a new code for the next entry
            console.log('创建成功的档案数据：', response.data);
          } else {
            // Backend returned an error (e.g., 400 validation error, 500 server error)
            // The response.data in your error example is a string, so check that.
            let errorMessage = '档案添加失败，请重试。';
            if (response && response.msg) {
              errorMessage = response.msg;
            }
            if (response && response.data && typeof response.data === 'string') {
              // Parse the stringified error detail if it exists
              try {
                const errorData = JSON.parse(response.data);
                if (errorData.archive_name) {
                  errorMessage = `档案名称：${errorData.archive_name.join(', ')}`;
                } else if (errorData.archive_description) {
                  errorMessage = `档案描述：${errorData.archive_description.join(', ')}`;
                } else if (errorData.archive_code) { // For the unique code generation error
                  errorMessage = `档案号：${errorData.archive_code.join(', ')}`;
                }
              } catch (e) {
                // If it's not a parsable JSON string, use the default error message
                console.error("Error parsing backend error message:", e);
              }
            }

            ElMessage.error(errorMessage);
          }
        } catch (error) {
          // Catch any network errors or uncaught exceptions during the API call
          console.error('Error submitting form:', error);
          ElMessage.error('网络或服务器错误，请稍后再试。');
        } finally {
          loading.value = false; // Always set loading to false after the request
        }
      } else {
        ElMessage.error('请填写完整的档案信息。');
      }
    };

    // Initialize an archive code when the component mounts
    onMounted(() => {
      generateCode();
    });

    return { form, rules, formRef, generateCode, submitForm, loading };
  },
});
</script>

<style scoped>
.ml-2 {
  margin-left: 8px;
}
.mb-4 {
  margin-bottom: 20px;
}
</style>