import { createApp } from 'vue';
import ElementPlus from 'element-plus';
import 'element-plus/dist/index.css';
import App from './App.vue';
import router from './router';
import { createPinia } from 'pinia';
import { zhCn } from 'element-plus/es/locales.mjs';
const app = createApp(App);
const pinia = createPinia();
app.use(pinia);
app.use(ElementPlus,{ locale: zhCn });
app.use(router);
app.mount('#app');
